### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Farizov** [bitstuffing/pychat#1]
gpt4free.py", line 29, in __init__
    cookie = response.text.split('sessionId&#34;:&#34;N\/A&#34;,&#34;restNonce&#34;:&#34;')[1].split('&#34;,&#34;')[0]
IndexError: list index out of range

**Comment by bitstuffing** [comment]
Hi there,

Thanks for use pychat and the report. 

I see that this provider has changed his page/algorithm. 

 I need to investigate how to solve (and if it's possible, because I saw in his page that gpt4 is not working, and gpt3.5 is working in the page). Also I'm watching that gpt petitions are requesting to gpt-god page, and for that it's requiring a login, so... I need to investigate what can we do with that.

Anyway, I get it, thank you for the report.

**Comment by Farizov** [comment]
Hello,

Thanks a lot for a quick response.

**Comment by bitstuffing** [comment]
done!

**Comment by Farizov** [comment]
Works great. Thanks!
